### ISSUE TITLE
Cannot work at node v4.5.0

### ISSUE THREAD

**Issue by Asoul** [kpman/newsroom#22]
```
> newsroom
/usr/local/lib/node_modules/newsroom-cli/src/main.js:6
const { error } = require('./utils/log');
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/newsroom-cli/src/cli.js:3:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

> node -v
v4.5.0
```

**Comment by MarkRabey** [comment]
I don't think that's a bug - `package.json` specifies Node >=7.6

Maybe could be documented better though.

**Comment by kpman** [comment]
@Asoul I will follow the nodejs LTS and support node version@4
@MarkRabey Thanks for giving the hint. I will add the node version on the readme soon.
